---
Resources:
  SimpleEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t3.micro
      ImageId: ami-06067086cf86c58e6 # AMI ID for your region
      Tags:
        - Key: Name
          Value: MySimpleInstance
